apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fsx
provisioner: fsx.csi.aws.com
parameters:
  subnetId: ${module.vpc.private_subnets[0]}
  securityGroupIds: ${aws_security_group.fsx.id}
  deploymentType: PERSISTENT_1
  automaticBackupRetentionDays: "1"
  dailyAutomaticBackupStartTime: "00:00"
  copyTagsToBackups: "true"
  perUnitStorageThroughput: "200"
  dataCompressionType: "NONE"
  weeklyMaintenanceStartTime: "7:09:00"
  fileSystemTypeVersion: "2.12"
mountOptions:
  - flock
