apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: tlvsummit23loader
spec:
  taints:
  - key: dedicated
    value: tlvsummit23loader
    effect: NoSchedule
  requirements:
#  - key: karpenter.k8s.aws/instance-generation
#    operator: In
#    values:
#    - "7"
#  - key: karpenter.k8s.aws/instance-cpu
#    operator: In
#    values:
#    - "4"
  - key: karpenter.sh/capacity-type
    operator: In
    values: 
    - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
    - amd64
  limits:
    resources:
      cpu: 90000
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: grv-use1
  securityGroupSelector:
    karpenter.sh/discovery: grv-use1
