apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: apploader
spec:
  requirements:
#  - key: karpenter.k8s.aws/instance-cpu
#    operator: In
#    values:
#    - "4"
  - key: karpenter.sh/capacity-type
    operator: In
    values: 
    - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
    - amd64
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: grv-use1
  securityGroupSelector:
    karpenter.sh/discovery: grv-use1
