---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lyraattacker
  name: lyraattacker
spec:
#  replicas: 1
  selector:
    matchLabels:
      app: lyraattacker
  template:
    metadata:
      labels:
        app: lyraattacker
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: apploader
      serviceAccountName: appsimulator
      containers:
      - env:
        - name: PORT
          value: "7777"
        - name: HOST
          value: "44.228.131.0"
        - name: NUM_OF_LOAD_THREADS
          value: "100"
        - name: SLEEP_BETWEEN_CYCLE
          value: "10"
        - name: DEPLOY_NAME
          value: "appsimulator"
        image: 907513986313.dkr.ecr.us-west-2.amazonaws.com/lyra:lyra_attacker
        imagePullPolicy: Always
        name: lyraattacker
        command: ["/simulate_session.py"]
        #resources:
        #  requests:
        #    cpu: 1000m
        #    memory: 512Mi
        #  limits:
        #    cpu: 1000m
        #    memory: 512Mi
