apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: orders
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/arch
      operator: In
      values: ["arm64"]
  limits:
    resources:
      cpu: 100000
  provider:
    amiFamily: AL2
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          volumeSize: 100Gi
          volumeType: gp3
          iops: 10000
          deleteOnTermination: true
          throughput: 125
    securityGroupSelector:
      karpenter.sh/discovery: mmo-us-west-2
      #kubernetes.io/cluster/mmo-us-west-2: '*'
    subnetSelector:
      karpenter.sh/discovery: mmo-us-west-2
      #kubernetes.io/cluster/mmo-us-west-2: '*'
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: orders
spec:
  subnetSelector:
    karpenter.sh/discovery: mmo-us-west-2
  securityGroupSelector:
    karpenter.sh/discovery: mmo-us-west-2
