apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stablediffusion-compile-inf
  name: stablediffusion-compile-inf
spec:
  selector:
    matchLabels:
      app: stablediffusion-compile-inf
  template:
    metadata:
      labels:
        app: stablediffusion-compile-inf
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: amd-neuron
      serviceAccountName: appsimulator
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: app
        image: 133573815653.dkr.ecr.us-west-2.amazonaws.com/stablediffusion:amd64-neuron
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        command: ["/start.sh"]
        args: ["compile"]
        resources:
          limits:
            aws.amazon.com/neuron: 2
        env:
        - name: AWS_NEURON_VISIBLE_DEVICES
          value: "ALL"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
