apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sd21-inf2-serve
  name: sd21-inf2-serve
spec:
  selector:
    matchLabels:
      app: sd21-inf2-serve
  template:
    metadata:
      labels:
        app: sd21-inf2-serve
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: amd-neuron
      serviceAccountName: appsimulator
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      initContainers:
      - name: pull-model-tar
        image: 133573815653.dkr.ecr.us-west-2.amazonaws.com/stablediffusion:amd64-neuron-assets
        imagePullPolicy: Always
        volumeMounts:
        - name: workdir
          mountPath: /model
        command:
        - /bin/bash
        - "-exc"
        - |
          set -x
          model="stable-diffusion-2-1-base"
          wget https://sdinfer.s3.us-west-2.amazonaws.com/${model}_xla.tar.gz -O /model/model.tar.gz
      containers:
      - name: app
        image: 133573815653.dkr.ecr.us-west-2.amazonaws.com/stablediffusion:amd64-neuron
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /app
            name: workdir
        command: ["/start.sh"]
        args: ["run"]
        resources:
          limits:
            aws.amazon.com/neuron: 6
        lifecycle:
          postStart:
            exec:
              command: ["/create_node_port_svc.sh"]
          preStop:
            exec:
              command: ["/bin/sh","-c","kubectl delete svc `kubectl get svc|grep $POD_NAME | awk '{print $1}'`"]
        env:
        - name: AWS_NEURON_VISIBLE_DEVICES
          value: "ALL"
        - name: MODEL_ID
          value: "stabilityai/stable-diffusion-2-1-base"
        - name: MODEL_FILE
          value: "stable-diffusion-2-1-base"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: workdir
        emptyDir: {}
      - name: dshm
        emptyDir:
          medium: Memory
