---
apiVersion: v1
kind: Namespace
metadata:
  name: "default"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-deployment
  namespace: default
  labels:
    app: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: stk
      containers:
        - name: nginx
          image: public.ecr.aws/nginx/nginx:1.21
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: eks-sample-service
  namespace: default
  labels:
    app: default
spec:
  type: NodePort
  selector:
    app: default
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
