---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: snap-use1
  region: us-east-1
  version: "1.27"
  tags:
    karpenter.sh/discovery: snap-use1

availabilityZones: ['us-east-1a','us-east-1b','us-east-1c','us-east-1d','us-east-1f']

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: karpenter
      namespace: karpenter
    roleName: snap-use1-karpenter
    attachPolicyARNs:
    - arn:aws:iam::953892292675:policy/KarpenterControllerPolicy-snap-use1
    roleOnly: true

iamIdentityMappings:
- arn: "arn:aws:iam::953892292675:role/KarpenterNodeRole-snap-use1"
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes

managedNodeGroups:
- instanceType: m5.large
  amiFamily: AmazonLinux2
  name: snap-use1-ng
  desiredCapacity: 2
  minSize: 1
  maxSize: 10
  availabilityZones: ['us-east-1a','us-east-1b','us-east-1c','us-east-1d','us-east-1f']
