---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: trn-use1
  region: us-east-1
  version: "1.27"
  tags:
    karpenter.sh/discovery: trn-use1

availabilityZones: ['us-east-1a','us-east-1f']

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: karpenter
      namespace: karpenter
    roleName: trn-use1-karpenter
    attachPolicyARNs:
    - arn:aws:iam::779991826153:policy/KarpenterControllerPolicy-trn-use1
    roleOnly: true

iamIdentityMappings:
- arn: "arn:aws:iam::779991826153:role/KarpenterNodeRole-trn-use1"
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes

managedNodeGroups:
- instanceType: m5.large
  amiFamily: AmazonLinux2
  name: trn-use1-ng
  desiredCapacity: 2
  minSize: 1
  maxSize: 10
