apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-cas
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: snap-cas-ng
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            limits:
              memory: 512Mi
              cpu: 1
            requests:
              cpu: 1
              memory: 512Mi
