apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: apps
spec:
  nodeSelector:
    karpenter.sh/provisioner-name: stk
  containers:
  - image: alpine
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: Always
    name: alpine
  restartPolicy: Always
