apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  #storageClassName: manual
  capacity:
    storage: 1800Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nvme1n1"
