apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
spec:
  nodeSelector:
    karpenter.sh/provisioner-name: trainium
  containers:
  - name: app
    image: public.ecr.aws/aws-cli/aws-cli:2.13.1
    command: ["/bin/sh", "-c"]
    args: ["while true; do sleep 30; done"]
#    volumeMounts:
#      - name: local-nvme1-vol
#        mountPath: /mnt/nvme1n1
#  volumes:
#    - name: local-nvme1-vol
#      hostPath:
#        path: /mnt/nvme1n1
