---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: rapid-scale-us-west-2
  region: us-west-2
  version: "1.23"
  tags:
    karpenter.sh/discovery: rapid-scale-us-west-2
managedNodeGroups:
  - instanceType: t4g.large
    amiFamily: AmazonLinux2
    name: rapid-scale-us-west-2-ng
    desiredCapacity: 2
    minSize: 1
    maxSize: 10
iam:
  withOIDC: true
addons:
- name: vpc-cni
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
