apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
  - key: karpenter.k8s.aws/instance-cpu
    operator: Lt
    values:
    - "4"
  #- key: node.kubernetes.io/instance-type
  #  operator: In
  #  values:
    #- "m6a.xlarge"
    #- "m6g.xlarge"
  #  - "m5.xlarge" 
  - key: karpenter.sh/capacity-type
    operator: In
    values: 
    - spot
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
    - amd64
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: rapid-scale-us-west-2
  securityGroupSelector:
    karpenter.sh/discovery: rapid-scale-us-west-2
