apiVersion: v1
kind: Service
metadata:
  name: craft-svc
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-name: "craft"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "4080"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: TCP
spec:
  selector:
    app: craft
  ports:
    - protocol: TCP
      port: 4080
      targetPort: 4080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: craft
  name: craft
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: craft
  template:
    metadata:
      name: craft
      labels:
        app: craft
    spec:
      shareProcessNamespace: true
      nodeSelector:
        karpenter.sh/provisioner-name: craft
      #terminationGracePeriodSeconds: 120
      serviceAccountName: adaptivecraft
      volumes:
      - name: secrets-store-craft
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: craft
      containers:
      - name: initdb
        volumeMounts:
        - name: secrets-store-craft
          mountPath: "/mnt/secrets"
        env:
            - name: IS_AGONES
              value: "False"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVERPORT
              value: "4080"
            - name: BUFFER_SIZE
              value: "8192"
            - name: SPAWN_X
              value: "832"
            - name: SPAWN_Y
              value: "37"
            - name: SPAWN_Z
              value: "192"
            - name: MAX_SESSIONS_IN_GS
              value: "3"
            - name: DEPLOY_NAME
              value: "craft"
            - name: SCALE_UP_COOLDOWN
              value: "60"
            - name: USE_AUTH
              value: "True"
            - name: RECORD_HISTORY
              value: "true"
            - name: AUTH_SRV
              value: "http://craft.auth.yahav.sa.aws.dev/auth/identity/"
            - name: SECRET_FILE
              value: "/mnt/secrets/craftcraftusw2SecretAA604F6-CbrgEOMoOlpW"
        image: 953892292675.dkr.ecr.us-west-2.amazonaws.com/craft-ci:craft-multiarch
        imagePullPolicy: Always
        command: ["/start.sh"]
        readinessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
        livenessProbe:
            tcpSocket:
              port: 4080
            initialDelaySeconds: 5
            periodSeconds: 10
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "/create_node_port_svc.sh"]
            preStop:
              exec:
                # Allow existing clients to complete within 120 seconds
                # command: ["/bin/sh", "-c", "kill $(ps aux | grep server.py| grep -v grep| awk '{print $2}') && sleep 120"]
                command: ["/bin/sh","-c","kubectl delete svc `kubectl get svc|grep $MY_POD_NAME | awk '{print $1}'`"]
        resources:
            requests:
              cpu: 1024m
              memory: 1024Mi
        ports:
          - containerPort: 4080
            protocol: TCP
            hostPort: 4080
