apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: craft
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "craftcraftusw2SecretAA604F6-CbrgEOMoOlpW"
          objectType: "secretsmanager"
