apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: snap
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: [on-demand]
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [c6g,c7g,m6g,m7g]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [large]
    - key: kubernetes.io/arch
      operator: In
      values: [arm64]
  limits:
    resources:
      cpu: 99999
  providerRef:
    name: default
  consolidation: 
    enabled: true
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: snap-cas-use1
  securityGroupSelector:
    karpenter.sh/discovery: snap-cas-use1
