apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simplemultiarchapp
  namespace: default
spec:
  maxReplicas: 100
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simplemultiarchapp
