apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: stk
spec:
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values: 
    - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
    - amd64
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 200Gi
        volumeType: gp3
        iops: 10000
        deleteOnTermination: true
        throughput: 125
  subnetSelector:
    karpenter.sh/subnet/discovery: ip6-usw2-public
  securityGroupSelector:
    karpenter.sh/discovery: ip6-usw2
  userData: |
    #!/bin/bash -x
    alloc_id=`aws ec2 describe-addresses --filters "Name=tag:game-name,Values=stk" --query "Addresses[?AssociationId==null].AllocationId" --output text | awk '{print $1}'`
    if [ -z "$alloc_id" ]; then
      alloc_id=`aws ec2 allocate-address --tag-specifications 'ResourceType=elastic-ip,Tags=[{Key=game-name,Value=stk},{Key=Name,Value=stk}]' --query "AllocationId" --output text`
    fi
    TOKEN=`curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
    instance_id=`curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-id`
    interface_id=`aws ec2 describe-network-interfaces --filters Name=tag:Name,Values=karpenter.sh/provisioner-name/stk --query "NetworkInterfaces[?Attachment.InstanceId == '$instance_id'].NetworkInterfaceId" --output text`
    aws ec2 associate-address --network-interface-id $interface_id --allocation-id $alloc_id 
