apiVersion: batch/v1
kind: CronJob
metadata:
  name: vacuum-logisitics
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
         serviceAccountName: appsimulator
         volumes:
         - name: secrets-store-orders
           csi:
             driver: secrets-store.csi.k8s.io
             readOnly: true
             volumeAttributes:
               secretProviderClass: rapidscale
         containers:
         - name: vacuum-pgp
           volumeMounts:
           - name: secrets-store-orders
             mountPath: "/mnt/secrets"
           env:
           - name: SECRET_FILE
             value: "/mnt/secrets/rapidscaleSecretFD8D90A13fd-erW3rRZJDUbZ"
           image: 274739860030.dkr.ecr.us-west-2.amazonaws.com/djangoapp:multiarch-py3
           imagePullPolicy: Always
           command: ["/usr/src/app/vacuum.sh"]
         restartPolicy: OnFailure 
