apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadsimu
  name: loadsimu
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadsimu
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loadsimu
    spec:
      containers:
      - command:
        - /usr/src/app/appsimulator.sh
        env:
        - name: QUEUE_URL
          value: https://sqs.us-east-1.amazonaws.com/907513986313/appsimulator
        - name: RADIAN_INTERVAL
          value: "0.3"
        - name: RADIAN_MAX
          value: "3.14"
        - name: CLIENT_SCALE_RATIO
          value: "1"
        - name: MIN_AT_CYCLE_START
          value: "1"
        - name: CLIENT_DEPLOY_PREFIX
          value: apploader
        - name: DEPLOY_NAME
          value: appsimulator
        - name: MIN_SLEEP_BETWEEN_CYCLE
          value: "15"
        - name: MAX_SLEEP_BETWEEN_CYCLE
          value: "15"
        image: 907513986313.dkr.ecr.us-west-2.amazonaws.com/simplemultiarchimage:multiarch-py3
        imagePullPolicy: Always
        name: loadsimu
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: appsimulator
      serviceAccountName: appsimulator
      terminationGracePeriodSeconds: 30
